AWSTemplateFormatVersion: "2010-09-09"

Resources:
  StateBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      VersioningConfiguration:
        Status: Enabled

  LockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "LockID"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        -
          AttributeName: "LockID"
          KeyType: "HASH"

Outputs:
  StateBucketName:
    Description: S3 state bucket name
    Value: !Ref StateBucket
  LockTableName:
    Description: DynamoDB lock table name
    Value: !Ref LockTable
